services:
  client:
    image: client-dev
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-dev
    ports:
      - '5173:5173'
  postgress:
    image: postgres:13
    container_name: postgress
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
  server:
    image: server-dev
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-dev
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - SECRET=mysecret
      - DATABASE_URL=postgres://postgres:mysecretpassword@postgress:5432/postgres
      - SERVER_URL=http://localhost:3001
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - postgress
