name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build client
        run: |
          cd client
          echo "Install dependencies"
          npm install
          echo "Build client"
          npm run build

      - name: Build backend
        run: |
          cd server
          npm install
          npm run build
          mv -R ../client/dist build/
          mv package.json build/
          mv package-lock.json build/
          rm -rf build/node_modules
          ls -R -a build/

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'server/build/*'
          target: '/home/page/temp'

      - name: Execute Deployment Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir /home/page/temp/server/build/images
            cd /home/page/server
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            mkdir -p /home/page/server/images
            if [ "$(ls -A /home/page/server/images)" ]; then
              mv /home/page/server/images/* /home/page/temp/server/build/images/
            else
              echo "POINT 5: No production images"
            fi
            rm -rf /home/page/server/* && mv /home/page/temp/server/build/* /home/page/server/
            rm -rf /home/page/temp
            cd /home/page/server
            cp ../ecosystem/ecosystem.config.js ./
            npm install
            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
